// MaSsExportPlugin
// Initial code generated by Softimage SDK Wizard
// Executed Mon May 5 23:21:18 UTC+0400 2014 by sshadows
// 
// Tip: You need to compile the generated code before you can load the plug-in.
// After you compile the plug-in, you can load it by clicking Update All in the Plugin Manager.
#include <xsi_application.h>
#include <xsi_context.h>
#include <xsi_pluginregistrar.h>
using namespace XSI; 

SICALLBACK XSILoadPlugin( PluginRegistrar& in_reg )
{
	in_reg.PutAuthor(L"sshadows");
	in_reg.PutName(L"MaSsExportPlugin");
	in_reg.PutVersion(1,0);
	in_reg.RegisterCommand(L"MaSsExport",L"MaSsExport");
	//RegistrationInsertionPoint - do not remove this line

	return CStatus::OK;
}

SICALLBACK XSIUnloadPlugin( const PluginRegistrar& in_reg )
{
	CString strPluginName;
	strPluginName = in_reg.GetName();
	Application().LogMessage(strPluginName + L" has been unloaded.",siVerboseMsg);
	return CStatus::OK;
}
